replicaCount: 1

image:
  repository: "606207925787.dkr.ecr.us-east-1.amazonaws.com/illuminati-django-backend"
  pullPolicy: Always
  tag: "v-1"


serviceAccountName: "backend-service-account"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

containerPort: 8000

podAnnotations: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70


db:
  name: "aWxsdW1pbmF0eQ=="
  user: "aWxsdW1pbmF0eQ=="
  password: "el00TWZ5d2JdaCxGV11HLA=="
  host: "dGVycmFmb3JtLTIwMjUxMTE0MDk1MzI0OTU0MzAwMDAwMDAyLmNzbGMwZTBpYWZjNC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20="
  port: "MzMwNg=="

secret: "c2VjcmV0"

external-secrets:
  enabled: false